# Site Info
title: '네주의 나만보는 개발로그'
tagline: '비전공자 네주머니의 나만보는 개발로그_갤로그'
description: '프로그래밍을 공부하며 배운점 느낀점을 기록하는 곳입니다.'
baseurl: ""
url: https://hjban-dev.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: BAN HYEJU
  description: 네주머니 (BAN HYEJU)
  contact:
    # linkedin:  https://www.linkedin.com/in/
    github:    https://github.com/hjban-dev
    # facebook:  https://hed-u.tistory.com/
    # twitter:   https://twitter.com/
    # weibo:     http://weibo.com/
    email:    mailto:baneju212@naver.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Categories:
    - '/blog/categories/'
    # - { Categories All: '/blog/categories/' }
    - { TIL (Today I Learned): '/blog/categories/#til' }
    # - { 컴퓨터공학 : '/blog/categories/#컴퓨터공학' }
    # - { Django: '/blog/categories/#django' }
    - { Algorithm: '/blog/categories/#algorithm' }
    - { Javascript: '/blog/categories/#javascript' }
    - { React: '/blog/categories/#react' }
    - { Nodejs: '/blog/categories/#nodejs' }
    - { MongoDB: '/blog/categories/#mongodb' }
    # - { MySQL: '/blog/categories/#MySQL' }
    - { Git: '/blog/categories/#git' }
    # - { firebase: '/blog/categories/#firebase' }
    - { etc: '/blog/categories/#etc' }
    # - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Tags:
    - '/blog/tags/'

# busuanzi - people statistics
busuanzi:
  enable: true
  src: //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
  page_pv: # page view count
    alert: <i class="fa fa-file"></i>
    unit: PAGE
  site_pv: # total site page view count
    alert: <i class="fa fa-eye"></i>
    unit: SITE
  site_uv: # user view count
    alert: <i class="fa fa-user"></i>
    unit: USER

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'


# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-154010929-1' # leave blank if you don't want google analytics
disqus_short_name: 'hjbandev' # leave blank if you don't want disqus


# Use the following plug-ins
gems:
  - jekyll-paginate
