# Site Info
title: '바네주의 나만보는 개발로그'
tagline: '비전공자 네주머니의 나만보는 개발로그_갤로그'
description: '프로그래밍을 공부하며 배운점 느낀점을 기록하는 곳입니다.'
baseurl: ""
url: https://hjban-dev.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: BAN HYEJU
  description: 네주머니 (BAN HYEJU)
  contact:
    # linkedin:  https://www.linkedin.com/in/
    github:    https://github.com/hjban-dev
    # facebook:  https://hed-u.tistory.com/
    # twitter:   https://twitter.com/
    # weibo:     http://weibo.com/
    email:    mailto:baneju212@naver.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/blog/'
  Categories:
    - '/'
    # - { Categories All: '/blog/categories/' }
    - { TIL (Today I Learned): '/blog/categories/#til' }
    # - { 컴퓨터공학 : '/blog/categories/#컴퓨터공학' }
    # - { Django: '/blog/categories/#django' }
    # - { Python: '/blog/categories/#python' }
    - { Javascript: '/blog/categories/#javascript' }
    - { Nodejs: '/blog/categories/#nodejs' }
    # - { MySQL: '/blog/categories/#MySQL' }
    # - { 알고리즘 문제풀이: '/blog/categories/#알고리즘-문제풀이' }
    - { git: '/blog/categories/#git' }
    # - { firebase: '/blog/categories/#firebase' }
    - { etc: '/blog/categories/#etc' }
    # - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Search:
    - '/search/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'


# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-92094009-1' # leave blank if you don't want google analytics
disqus_short_name: 'hjban-dev-github-io' # leave blank if you don't want disqus


# Use the following plug-ins
gems:
  - jekyll-paginate
